# vim:ts=2:sw=2:et:ai:sts=2
name: Upload release to PyPI

on:
  # Only run when release is created in the master branch
  release:
    types: [created]
    branches:
      - 'master'

jobs:
  build:
    name: 'Build distributable files'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        name: 'Checkout source repository'
        with:
            fetch-depth: 0

      - uses: actions/setup-python@v4

      - name: 'Build sdist and wheel'
        run: python3 setup.py sdist bdist_wheel

      - uses: actions/upload-artifact@v2
        name: 'Upload build artifacts'
        with:
          path: 'dist/*'

  upload_pypi:
    name: 'Upload packages'
    needs: ['build']
    runs-on: 'ubuntu-latest'
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/download-artifact@v3
        name: 'Download artifacts'
        with:
          name: 'artifact'
          path: 'dist'

      - uses: pypa/gh-action-pypi-publish@release/v1
        name: "Publish package to PyPI"
        with:
          user: '__token__'
          password: '${{ secrets.PYPI_API_TOKEN }}'